# Application config
output_dir: ./tmp/out
core_repo:
  url: https://github.com/Homebrew/homebrew-core.git
  branch: master
  dir: ./tmp/homebrew-core
  clone: true
reader:
  max_workers: 10
  derive_repo: true
  fallback_license: pseudo
